### ISSUE TITLE
Launcher does not deduplicate libraries

### ISSUE THREAD

**Issue by bigfoot547** [olauncher/olauncher#100]
New fabric versions expect the launcher to deduplicate libraries on the classpath. This launcher doesn't, and leads to things like this:
```
Exception in thread "main" java.lang.ExceptionInInitializerError
    at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.IllegalStateException: duplicate ASM classes found on classpath: jar:file:/C:/Porti/Applications/1/libraries/org/ow2/asm/asm/9.7.1/asm-9.7.1.jar!/org/objectweb/asm/ClassReader.class, jar:file:/C:/Porti/Applications/1/libraries/org/ow2/asm/asm/9.3/asm-9.3.jar!/org/objectweb/asm/ClassReader.class
    at net.fabricmc.loader.impl.util.LoaderUtil.verifyClasspath(LoaderUtil.java:83)
    at net.fabricmc.loader.impl.launch.knot.Knot.<clinit>(Knot.java:345)
    ... 1 more
```

**Comment by avs-origami** [comment]
seconding this, I have this issue too. I can work around it by manually deleting the folder at the right time, but it's really annoying. I would really love to see this fixed.

**Comment by TobyWarren** [comment]
Also have this issue, deleting the asm version conflicting just as the game launches does allow it to run. But that is a pain in the ***.

**Comment by SalC1** [comment]
Please fix this issue. Unable to run fabric on 1.21.4. Currently have to use a sketchy setup with a python script to delete the asm9.6 file every time I launch the game.

**Comment by T0biasCZe** [comment]
could you please share the sketchy python script?
