### ISSUE TITLE
Login wont work

### ISSUE THREAD

**Issue by commandcontrolQ** [olauncher/olauncher#101]
For some reason, regardless of how I try to log in, I cannot get OLauncher to work on my Debian installation.
Whenever I try to authenticate, I get one of the following errors on the launcher screen:
- `SocketException: Connection reset`
- `SocketException: Connect timed out`

Additionally, the browser I am using will say something like "You're now signed in to OLauncher. You can safely close this window." or "The code has been received. You may now close this window."

Terminal output below (personal details are censored):
```
Using working directory: /home/######/.minecraft
Interactive: yes
[16:21:28 INFO]: OLauncher 1.7.3_01 (through bootstrap 100) started on linux...
[16:21:28 INFO]: Current time is Dec 5, 2024, 4:21:28 PM
[16:21:28 INFO]: System.getProperty('os.name') == 'Linux'
[16:21:28 INFO]: System.getProperty('os.version') == '6.1.0-28-amd64'
[16:21:28 INFO]: System.getProperty('os.arch') == 'amd64'
[16:21:28 INFO]: System.getProperty('java.version') == '17.0.13'
[16:21:28 INFO]: System.getProperty('java.vendor') == 'Debian'
[16:21:28 INFO]: System.getProperty('sun.arch.data.model') == '64'
[16:21:28 INFO]: proxy == DIRECT
[16:21:28 INFO]: Refreshing local version list...
[16:21:28 INFO]: Refreshing remote version list...
[16:21:28 INFO]: It is not time to query releases yet. Wait another 152 minutes.
[16:21:28 INFO]: Latest release is v1.7.3_01 (ID 157441086).
[16:21:28 INFO]: Your java runtime platform is 'linux'.
[16:21:28 INFO]: Finished refreshing java runtime list.
[16:21:28 INFO]: Refresh complete.
[16:21:28 INFO]: Loaded profile Default
[16:21:28 INFO]: Loaded 1 profile(s); selected 'Default'
[16:22:09 WARN]: Failed to shut down scheduled executor in time... :(
[16:22:10 ERROR]: Couldn't log in
com.mojang.authlib.exceptions.AuthenticationException: I/O exception for request
        at dev.figboot.olauncher.auth.MicrosoftAuthenticationService.makeRequest(MicrosoftAuthenticationService.java:146) ~[patched.jar:1.7.3_01]
        at dev.figboot.olauncher.auth.MicrosoftAuthenticationService.makeRequest(MicrosoftAuthenticationService.java:118) ~[patched.jar:1.7.3_01]
        at dev.figboot.olauncher.auth.MicrosoftAuthenticationService.post(MicrosoftAuthenticationService.java:153) ~[patched.jar:1.7.3_01]
        at dev.figboot.olauncher.auth.MicrosoftUserAuthentication.xblLogIn(MicrosoftUserAuthentication.java:210) ~[patched.jar:1.7.3_01]
        at dev.figboot.olauncher.auth.MicrosoftUserAuthentication.logIn(MicrosoftUserAuthentication.java:113) ~[patched.jar:1.7.3_01]
        at net.minecraft.launcher.ui.popups.login.LogInForm$2.run(LogInForm.java:165) ~[patched.jar:1.7.3_01]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.net.SocketException: Connection reset
        at sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:328) ~[?:?]
        at sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:355) ~[?:?]
        at sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:808) ~[?:?]
        at java.net.Socket$SocketInputStream.read(Socket.java:966) ~[?:?]
        at sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:484) ~[?:?]
        at sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:478) ~[?:?]
        at sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:160) ~[?:?]
        at sun.security.ssl.SSLTransport.decode(SSLTransport.java:111) ~[?:?]
        at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1510) ~[?:?]
        at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1425) ~[?:?]
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:455) ~[?:?]
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:426) ~[?:?]
        at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:589) ~[?:?]
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:187) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1465) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1436) ~[?:?]
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:220) ~[?:?]
        at dev.figboot.olauncher.auth.MicrosoftAuthenticationService.makeRequest(MicrosoftAuthenticationService.java:139) ~[patched.jar:1.7.3_01]
        ... 8 more
[16:22:17 INFO]: Window closed, shutting down.
[16:22:17 INFO]: Halting executors
[16:22:17 INFO]: Awaiting termination.
[16:22:17 INFO]: Goodbye.
```

**Comment by commandcontrolQ** [comment]
The issue has been solved. Turns out the network I was connected to (public WiFi) had probably blocked something that the launcher needed to authenticate.
