### ISSUE TITLE
olauncher not installing

### ISSUE THREAD

**Issue by Bt-7274a** [olauncher/olauncher#16]
after deleting the launcher profiles folder and logging in it doesn't login the green bar thing never goes away

**Comment by bigfoot547** [comment]
Can you provide a screenshot or video? Try specifying a new working directory with the `--workDir` argument, something like: `java -jar olauncher-XXX.jar --workDir olaunchertemp`.

**Comment by Bt-7274a** [comment]
![Screenshot 2022-11-22 122907](https://user-images.githubusercontent.com/118773240/203314314-e7ffce95-f007-4b2e-a36a-b219a3e7bb17.png)
so if you can see the screenshot the green bar thing under login with microsoft just keeps going round and round infinitely

**Comment by Bt-7274a** [comment]
also i tried running java -jar olauncher-1.7.2_05-redist.jar --workDir olaunchertemp but just did the same

**Comment by Bt-7274a** [comment]
i think i found the error cuz there is a FATAL thing in the cmd output

**Comment by Bt-7274a** [comment]
error: [18:37:01 FATAL]: Unhandled exception in thread Thread[pool-2-thread-2,5,main]
java.lang.IllegalArgumentException: Name and ID cannot both be blank (first 2 lines of it)

**Comment by bigfoot547** [comment]
What about the rest of the stack trace?

**Comment by Bt-7274a** [comment]
what is a stack trace?
im assuming its this
[21:24:13 FATAL]: Unhandled exception in thread Thread[pool-2-thread-2,5,main]
java.lang.IllegalArgumentException: Name and ID cannot both be blank
        at com.mojang.authlib.GameProfile.<init>(GameProfile.java:16) ~[patched.jar:1.7.2_05]
        at dev.figboot.olauncher.auth.MicrosoftUserAuthentication.profileLogIn(MicrosoftUserAuthentication.java:215) ~[patched.jar:1.7.2_05]
        at dev.figboot.olauncher.auth.MicrosoftUserAuthentication.logIn(MicrosoftUserAuthentication.java:133) ~[patched.jar:1.7.2_05]
        at net.minecraft.launcher.ui.popups.login.LogInForm$4.run(LogInForm.java:168) ~[patched.jar:1.7.2_05]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by Bt-7274a** [comment]
huh i think its working again

**Comment by bigfoot547** [comment]
Strange. Maybe it was some issue with Mojang's API. Please reopen the issue if the issue comes back.
