### ISSUE TITLE
1.8 cheatbreaker 2 probleme

### ISSUE THREAD

**Issue by frivoxfr** [olauncher/olauncher#17]
https://youtu.be/PQ4jHyYpI0o

**Comment by bigfoot547** [comment]
That's definitely an issue. Can you please provide me with the launcher log and JSON file in the cheatbreaker preview folder? thanks

**Comment by frivoxfr** [comment]
https://www.mediafire.com/file/pku66hgv6ic27s3/CheatBreaker-preview-1.8.9.json/file

**Comment by frivoxfr** [comment]
https://youtu.be/BvT660WxhcA

**Comment by frivoxfr** [comment]
i test this but when i launch my game crash

**Comment by frivoxfr** [comment]
Setting user: FRIV0X
Setting UUID: 04eb124e1fc1419d8d1ee2998e94370d
Exception in thread "Client thread" java.lang.NoSuchMethodError: org.apache.commons.lang3.Validate.inclusiveBetween(JJJLjava/lang/String;)V
	at IllIIIIIIllIIIIlIlIllIIlI.<init>(Unknown Source)
	at llIlIIIllIlIlIllIIIlIIIll.lIIIIIIlIIllllIIlIIIlllII(Unknown Source)
	at llIlIIIllIlIlIllIIIlIIIll.<clinit>(Unknown Source)
	at llllllllIIIIIIIIIIllllllI.IIlIIIIIIIIIIlllIIllIlllI(Unknown Source)
	at lIlIlIlIIllIlllIllIllIlll.llIlIIlIIllllIlIIllIIIlll(Unknown Source)
	at lIIIlIIlIlIIllIIIIllIllIl.<init>(Unknown Source)
	at net.minecraft.client.main.Main.main(Unknown Source)
Stopping server

**Comment by bigfoot547** [comment]
The log you provided is the game output, not the launcher log. Anyway, I think I've found the issue with the json file. It seems like its "release type" is set to "preview" which does not mean anything to the launcher (it should be "snapshot", "release", "old_alpha", or "old_beta"). Perhaps I will edit the file to allow unknown types as well and file them under "other".

In the meantime, try editing the line in the json file that says `"type": "preview"` and replace it with `"type": "release"` and see if that makes it visible.

**Comment by frivoxfr** [comment]
thanks it fix

**Comment by bigfoot547** [comment]
Nice, I'm glad. I'll keep this issue open until I fix the actual bug.
