### ISSUE TITLE
Can't launch release version 1.6.4

### ISSUE THREAD

**Issue by Daisreich** [olauncher/olauncher#22]
Every time i try to play 1.6.4 i get this error in the launcher logs
`[22:39:59 ERROR]: Error setting up bundled java runtime
java.lang.NullPointerException: null
	at com.mojang.launcher.game.runner.AbstractGameRunner.ensureRuntime(AbstractGameRunner.java:147) ~[patched.jar:1.7.2_05]
	at com.mojang.launcher.game.runner.AbstractGameRunner.playGame(AbstractGameRunner.java:125) ~[patched.jar:1.7.2_05]
	at net.minecraft.launcher.game.GameLaunchDispatcher$1.run(GameLaunchDispatcher.java:120) ~[patched.jar:1.7.2_05]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:1.8.0_202]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:1.8.0_202]
	at java.lang.Thread.run(Unknown Source) ~[?:1.8.0_202]
`

**Comment by bigfoot547** [comment]
I believe this issue is already fixed, I just haven't made a hotfix for it yet. It seems like multiple people are having this issue so I'm gonna do that soon.

**Comment by bigfoot547** [comment]
There you go. Minecraft 1.6.4 works in hotfix 6.
