### ISSUE TITLE
Launcher stuck in loading state

### ISSUE THREAD

**Issue by pauhull** [olauncher/olauncher#23]
When launching, launcher is stuck in loading screen.

Log:
```
Using working directory: C:\Users\Paul\AppData\Roaming\.minecraft
Interactive: yes
[16:05:32 INFO]: OLauncher 1.7.2_06 (through bootstrap 100) started on windows...
[16:05:32 INFO]: Current time is Jan 12, 2023 4:05:32 PM
[16:05:32 INFO]: System.getProperty('os.name') == 'Windows 10'
[16:05:32 INFO]: System.getProperty('os.version') == '10.0'
[16:05:32 INFO]: System.getProperty('os.arch') == 'amd64'
[16:05:32 INFO]: System.getProperty('java.version') == '1.8.0_321'
[16:05:32 INFO]: System.getProperty('java.vendor') == 'Oracle Corporation'
[16:05:32 INFO]: System.getProperty('sun.arch.data.model') == '64'
[16:05:32 INFO]: proxy == DIRECT
[16:05:32 INFO]: JFX is already initialized
[16:05:32 INFO]: Refreshing local version list...
[16:05:32 INFO]: It is not time to query releases yet. Wait another 178 minutes.
[16:05:32 INFO]: Latest release is v1.7.2_06 (ID 88232471).
[16:05:33 INFO]: Refreshing remote version list...
[16:05:34 INFO]: Your java runtime platform is 'windows-x64'.
[16:05:34 INFO]: Finished refreshing java runtime list.
[16:05:34 INFO]: Refresh complete.
[16:05:34 ERROR]: Unexpected exception refreshing profile list
java.lang.NullPointerException: null
        at net.minecraft.launcher.Launcher$2.run(Launcher.java:213) ~[patched.jar:1.7.2_06]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_321]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_321]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:1.8.0_321]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:1.8.0_321]
        at java.lang.Thread.run(Unknown Source) ~[?:1.8.0_321]
[16:05:34 ERROR]: Unhandled exception in executor com.mojang.launcher.updater.ExceptionalThreadPoolExecutor$ExceptionalFutureTask@2982ba28
java.util.concurrent.ExecutionException: java.lang.NullPointerException
        at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_321]
        at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_321]
        at com.mojang.launcher.updater.ExceptionalThreadPoolExecutor$ExceptionalFutureTask.done(ExceptionalThreadPoolExecutor.java:60) ~[patched.jar:1.7.2_06]
        at java.util.concurrent.FutureTask.finishCompletion(Unknown Source) ~[?:1.8.0_321]
        at java.util.concurrent.FutureTask.setException(Unknown Source) ~[?:1.8.0_321]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_321]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:1.8.0_321]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:1.8.0_321]
        at java.lang.Thread.run(Unknown Source) ~[?:1.8.0_321]
Caused by: java.lang.NullPointerException
        at net.minecraft.launcher.profile.ProfileManager.saveProfiles(ProfileManager.java:66) ~[patched.jar:1.7.2_06]
        at net.minecraft.launcher.SwingUserInterface.showLoginPrompt(SwingUserInterface.java:177) ~[patched.jar:1.7.2_06]
        at net.minecraft.launcher.Launcher.ensureLoggedIn(Launcher.java:266) ~[patched.jar:1.7.2_06]
        at net.minecraft.launcher.Launcher$2.run(Launcher.java:242) ~[patched.jar:1.7.2_06]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_321]
        ... 4 more
[16:05:34 FATAL]: Unhandled exception in thread Thread[AWT-EventQueue-0,6,main]
java.lang.NullPointerException: null
        at net.minecraft.launcher.ui.bottombar.ProfileSelectionPanel.populateProfiles(ProfileSelectionPanel.java:81) ~[patched.jar:1.7.2_06]
        at net.minecraft.launcher.ui.bottombar.ProfileSelectionPanel$1.run(ProfileSelectionPanel.java:75) ~[patched.jar:1.7.2_06]
        at java.awt.event.InvocationEvent.dispatch(Unknown Source) ~[?:1.8.0_321]
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source) ~[?:1.8.0_321]
        at java.awt.EventQueue.access$500(Unknown Source) ~[?:1.8.0_321]
        at java.awt.EventQueue$3.run(Unknown Source) ~[?:1.8.0_321]
        at java.awt.EventQueue$3.run(Unknown Source) ~[?:1.8.0_321]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_321]
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source) ~[?:1.8.0_321]
        at java.awt.EventQueue.dispatchEvent(Unknown Source) ~[?:1.8.0_321]
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source) ~[?:1.8.0_321]
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source) ~[?:1.8.0_321]
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source) ~[?:1.8.0_321]
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source) ~[?:1.8.0_321]
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source) ~[?:1.8.0_321]
        at java.awt.EventDispatchThread.run(Unknown Source) ~[?:1.8.0_321]
```

Edit: 
Deleting launcher_profiles.json fixes this issue. Maybe the launcher should just fail silently or make a backup and delete the old file.

**Comment by bigfoot547** [comment]
Yeah, this bug is notorious. I need to actually fix it sooner or later. I'll take a crack at it when I have time. Thanks for making the issue.

**Comment by bigfoot547** [comment]
Tracked in #21
