### ISSUE TITLE
Launcher crashes Java

### ISSUE THREAD

**Issue by jadenquinn** [olauncher/olauncher#39]
Before I even get to use the launcher, I get this Java crash. This is before anything on the launcher window loads, still being a white screen.
This is on a Mac Pro (2008) with upgraded GPU (still happens on original 8800 GT), upgraded (kind of) RAM (667MHz instead of 800MHz, but 8GB over 2GB, still happens on original 800MHz RAM), and I checked the readme and it said to rename the laucher_profiles.json (or delete it or something), but this had zero effect. Still crashes at the exact same time in the same way.

Crash:
https://pastebin.com/UT5cYd0e

**Comment by jadenquinn** [comment]
Ok this is strange. I went to try and see if I could launch the launcher jar using Java 8 update 301 instead of 371 or whatever it was launching with before, so I used Terminal to do so, and it appears to work now, no idea why. Still crashes on J8U371/whatever though.

**Comment by bigfoot547** [comment]
Weird. Can you try another jvm? This may be upstream from the launcher, seems jfx-related.

**Comment by jadenquinn** [comment]
Ok great now I got stuff to download, but the game won't launch.
Launcher Log: [16:31:58 INFO]: Job 'Java Runtime' finished successfully (took 00:00:43.877)
[16:31:58 INFO]: Launching game
[16:31:58 INFO]: Unpacking natives to /Users/jaden/Library/Application Support/minecraft/versions/1.0/1.0-natives-1646526148599
[16:31:58 INFO]: Reconstructing virtual assets folder at resources
[16:31:58 INFO]: Copying asset for virtual or resource-mapped: resources/READ_ME_I_AM_VERY_IMPORTANT
[16:31:58 ERROR]: Couldn't unpack natives!
java.io.IOException: Cannot create directory 'resources'.
	at org.apache.commons.io.FileUtils.mkdirs(FileUtils.java:2200) ~[patched.jar:1.7.2_09]
	at org.apache.commons.io.FileUtils.createParentDirectories(FileUtils.java:1113) ~[patched.jar:1.7.2_09]
	at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:843) ~[patched.jar:1.7.2_09]
	at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:783) ~[patched.jar:1.7.2_09]
	at net.minecraft.launcher.game.MinecraftGameRunner.reconstructAssets(MinecraftGameRunner.java:292) ~[patched.jar:1.7.2_09]
	at net.minecraft.launcher.game.MinecraftGameRunner.launchGame(MinecraftGameRunner.java:137) ~[patched.jar:1.7.2_09]
	at com.mojang.launcher.game.runner.AbstractGameRunner.onDownloadJobFinished(AbstractGameRunner.java:292) ~[patched.jar:1.7.2_09]
	at com.mojang.launcher.game.runner.AbstractGameRunner$1.onDownloadJobFinished(AbstractGameRunner.java:179) ~[patched.jar:1.7.2_09]
	at com.mojang.launcher.updater.download.DownloadJob.popAndDownload(DownloadJob.java:150) ~[patched.jar:1.7.2_09]
	at com.mojang.launcher.updater.download.DownloadJob.access$000(DownloadJob.java:16) ~[patched.jar:1.7.2_09]
	at com.mojang.launcher.updater.download.DownloadJob$1.run(DownloadJob.java:111) ~[patched.jar:1.7.2_09]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_301]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_301]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_301]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_301]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_301]

**Comment by jadenquinn** [comment]
Btw that's what I did in my previous comment which worked.

**Comment by bigfoot547** [comment]
Hmm, that backtrace is not super debuggable. It's gotta be some permissions issue, but I can't be sure from what's there.

**Comment by FandyME** [comment]
> It wouldn't be a terrible idea to migrate olauncher to using the new file IO APIs, but until that happens, we're going to have to debug this another way. Can you create the resources directory yourself? Is it write protected? Is there some reason java wouldn't be able to write there?

Have the same issue here. I created the resources directory manually but still error, checked that it is not write protected and couldn't find any reason why java cant write in there. The directory in the default .minecraft directory in %Appdata%

**Comment by liam2211** [comment]
Giving javaw.exe Administrator privileges in the Properties pop-up fixes the issue for me. I do not recommend doing this for the security implications it has, but maybe this will help in debugging! :)

**Comment by Pwnz0rserver2009** [comment]
> Giving javaw.exe Administrator privileges in the Properties pop-up fixes the issue for me. I do not recommend doing this for the security implications it has, but maybe this will help in debugging! :)

OP is on a Mac

**Comment by liam2211** [comment]
That's correct, however the same issue on Windows 7 has been marked duplicate of this one, so this seems like the right place for my comment.
