### ISSUE TITLE
Launcher stuck on loading

### ISSUE THREAD

**Issue by manOnWebs** [olauncher/olauncher#41]
Yes i know this is already an issue.

`[16:06:23 INFO]: OLauncher 1.7.2_09 (through bootstrap 100) started on windows...
[16:06:23 INFO]: Current time is Aug 7, 2023 4:06:23 PM
[16:06:23 INFO]: System.getProperty('os.name') == 'Windows 11'
[16:06:23 INFO]: System.getProperty('os.version') == '10.0'
[16:06:23 INFO]: System.getProperty('os.arch') == 'amd64'
[16:06:23 INFO]: System.getProperty('java.version') == '1.8.0_381'
[16:06:23 INFO]: System.getProperty('java.vendor') == 'Oracle Corporation'
[16:06:23 INFO]: System.getProperty('sun.arch.data.model') == '64'
[16:06:23 INFO]: proxy == DIRECT
[16:06:23 INFO]: JFX is already initialized
[16:06:24 INFO]: Refreshing local version list...
[16:06:24 INFO]: Querying latest release...
[16:06:24 INFO]: Refreshing remote version list...
[16:06:24 INFO]: Refresh complete.
[16:06:24 INFO]: Your java runtime platform is 'windows-x64'.
[16:06:24 INFO]: Finished refreshing java runtime list.
[16:06:24 ERROR]: Unexpected exception refreshing profile list
java.lang.NullPointerException: null
	at net.minecraft.launcher.Launcher$2.run(Launcher.java:213) ~[patched.jar:1.7.2_09]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_381]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_381]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:1.8.0_381]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:1.8.0_381]
	at java.lang.Thread.run(Unknown Source) ~[?:1.8.0_381]
[16:06:24 FATAL]: Unhandled exception in thread Thread[AWT-EventQueue-0,6,main]
java.lang.NullPointerException: null
	at net.minecraft.launcher.ui.bottombar.ProfileSelectionPanel.populateProfiles(ProfileSelectionPanel.java:81) ~[patched.jar:1.7.2_09]
	at net.minecraft.launcher.ui.bottombar.ProfileSelectionPanel$1.run(ProfileSelectionPanel.java:75) ~[patched.jar:1.7.2_09]
	at java.awt.event.InvocationEvent.dispatch(Unknown Source) ~[?:1.8.0_381]
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source) ~[?:1.8.0_381]
	at java.awt.EventQueue.access$500(Unknown Source) ~[?:1.8.0_381]
	at java.awt.EventQueue$3.run(Unknown Source) ~[?:1.8.0_381]
	at java.awt.EventQueue$3.run(Unknown Source) ~[?:1.8.0_381]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_381]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source) ~[?:1.8.0_381]
	at java.awt.EventQueue.dispatchEvent(Unknown Source) ~[?:1.8.0_381]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source) ~[?:1.8.0_381]
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source) ~[?:1.8.0_381]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source) ~[?:1.8.0_381]
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source) ~[?:1.8.0_381]
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source) ~[?:1.8.0_381]
	at java.awt.EventDispatchThread.run(Unknown Source) ~[?:1.8.0_381]
[16:06:24 ERROR]: Unhandled exception in executor com.mojang.launcher.updater.ExceptionalThreadPoolExecutor$ExceptionalFutureTask@4c979c10
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_381]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_381]
	at com.mojang.launcher.updater.ExceptionalThreadPoolExecutor$ExceptionalFutureTask.done(ExceptionalThreadPoolExecutor.java:60) ~[patched.jar:1.7.2_09]
	at java.util.concurrent.FutureTask.finishCompletion(Unknown Source) ~[?:1.8.0_381]
	at java.util.concurrent.FutureTask.setException(Unknown Source) ~[?:1.8.0_381]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_381]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:1.8.0_381]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:1.8.0_381]
	at java.lang.Thread.run(Unknown Source) ~[?:1.8.0_381]
Caused by: java.lang.NullPointerException
	at net.minecraft.launcher.profile.ProfileManager.saveProfiles(ProfileManager.java:66) ~[patched.jar:1.7.2_09]
	at net.minecraft.launcher.SwingUserInterface.showLoginPrompt(SwingUserInterface.java:179) ~[patched.jar:1.7.2_09]
	at net.minecraft.launcher.Launcher.ensureLoggedIn(Launcher.java:266) ~[patched.jar:1.7.2_09]
	at net.minecraft.launcher.Launcher$2.run(Launcher.java:242) ~[patched.jar:1.7.2_09]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_381]
	... 4 more
[16:06:26 INFO]: Latest release is v1.7.2_09 (ID 110915754).
[16:06:48 FATAL]: Unhandled exception in thread Thread[AWT-EventQueue-0,6,main]
java.lang.NullPointerException: null
	at net.minecraft.launcher.profile.Profile.<init>(Profile.java:34) ~[patched.jar:1.7.2_09]
	at net.minecraft.launcher.ui.bottombar.ProfileSelectionPanel.actionPerformed(ProfileSelectionPanel.java:130) ~[patched.jar:1.7.2_09]
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source) ~[?:1.8.0_381]
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source) ~[?:1.8.0_381]
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source) ~[?:1.8.0_381]
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source) ~[?:1.8.0_381]
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source) ~[?:1.8.0_381]
	at java.awt.Component.processMouseEvent(Unknown Source) ~[?:1.8.0_381]
	at javax.swing.JComponent.processMouseEvent(Unknown Source) ~[?:1.8.0_381]
	at java.awt.Component.processEvent(Unknown Source) ~[?:1.8.0_381]
	at java.awt.Container.processEvent(Unknown Source) ~[?:1.8.0_381]
	at java.awt.Component.dispatchEventImpl(Unknown Source) ~[?:1.8.0_381]
	at java.awt.Container.dispatchEventImpl(Unknown Source) ~[?:1.8.0_381]
	at java.awt.Component.dispatchEvent(Unknown Source) ~[?:1.8.0_381]
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source) ~[?:1.8.0_381]
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source) ~[?:1.8.0_381]
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source) ~[?:1.8.0_381]
	at java.awt.Container.dispatchEventImpl(Unknown Source) ~[?:1.8.0_381]
	at java.awt.Window.dispatchEventImpl(Unknown Source) ~[?:1.8.0_381]
	at java.awt.Component.dispatchEvent(Unknown Source) ~[?:1.8.0_381]
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source) ~[?:1.8.0_381]
	at java.awt.EventQueue.access$500(Unknown Source) ~[?:1.8.0_381]
	at java.awt.EventQueue$3.run(Unknown Source) ~[?:1.8.0_381]
	at java.awt.EventQueue$3.run(Unknown Source) ~[?:1.8.0_381]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_381]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source) ~[?:1.8.0_381]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source) ~[?:1.8.0_381]
	at java.awt.EventQueue$4.run(Unknown Source) ~[?:1.8.0_381]
	at java.awt.EventQueue$4.run(Unknown Source) ~[?:1.8.0_381]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_381]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source) ~[?:1.8.0_381]
	at java.awt.EventQueue.dispatchEvent(Unknown Source) ~[?:1.8.0_381]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source) ~[?:1.8.0_381]
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source) ~[?:1.8.0_381]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source) ~[?:1.8.0_381]
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source) ~[?:1.8.0_381]
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source) ~[?:1.8.0_381]
	at java.awt.EventDispatchThread.run(Unknown Source) ~[?:1.8.0_381]
[16:06:49 FATAL]: Unhandled exception in thread Thread[AWT-EventQueue-0,6,main]
java.lang.NullPointerException: null
	at net.minecraft.launcher.profile.Profile.<init>(Profile.java:34) ~[patched.jar:1.7.2_09]
	at net.minecraft.launcher.ui.popups.profile.ProfileEditorPopup.<init>(ProfileEditorPopup.java:42) ~[patched.jar:1.7.2_09]
	at net.minecraft.launcher.ui.popups.profile.ProfileEditorPopup.showEditProfileDialog(ProfileEditorPopup.java:130) ~[patched.jar:1.7.2_09]
	at net.minecraft.launcher.ui.bottombar.ProfileSelectionPanel.actionPerformed(ProfileSelectionPanel.java:141) ~[patched.jar:1.7.2_09]
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source) ~[?:1.8.0_381]
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source) ~[?:1.8.0_381]
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source) ~[?:1.8.0_381]
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source) ~[?:1.8.0_381]
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source) ~[?:1.8.0_381]
	at java.awt.Component.processMouseEvent(Unknown Source) ~[?:1.8.0_381]
	at javax.swing.JComponent.processMouseEvent(Unknown Source) ~[?:1.8.0_381]
	at java.awt.Component.processEvent(Unknown Source) ~[?:1.8.0_381]
	at java.awt.Container.processEvent(Unknown Source) ~[?:1.8.0_381]
	at java.awt.Component.dispatchEventImpl(Unknown Source) ~[?:1.8.0_381]
	at java.awt.Container.dispatchEventImpl(Unknown Source) ~[?:1.8.0_381]
	at java.awt.Component.dispatchEvent(Unknown Source) ~[?:1.8.0_381]
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source) ~[?:1.8.0_381]
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source) ~[?:1.8.0_381]
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source) ~[?:1.8.0_381]
	at java.awt.Container.dispatchEventImpl(Unknown Source) ~[?:1.8.0_381]
	at java.awt.Window.dispatchEventImpl(Unknown Source) ~[?:1.8.0_381]
	at java.awt.Component.dispatchEvent(Unknown Source) ~[?:1.8.0_381]
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source) ~[?:1.8.0_381]
	at java.awt.EventQueue.access$500(Unknown Source) ~[?:1.8.0_381]
	at java.awt.EventQueue$3.run(Unknown Source) ~[?:1.8.0_381]
	at java.awt.EventQueue$3.run(Unknown Source) ~[?:1.8.0_381]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_381]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source) ~[?:1.8.0_381]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source) ~[?:1.8.0_381]
	at java.awt.EventQueue$4.run(Unknown Source) ~[?:1.8.0_381]
	at java.awt.EventQueue$4.run(Unknown Source) ~[?:1.8.0_381]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_381]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source) ~[?:1.8.0_381]
	at java.awt.EventQueue.dispatchEvent(Unknown Source) ~[?:1.8.0_381]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source) ~[?:1.8.0_381]
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source) ~[?:1.8.0_381]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source) ~[?:1.8.0_381]
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source) ~[?:1.8.0_381]
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source) ~[?:1.8.0_381]
	at java.awt.EventDispatchThread.run(Unknown Source) ~[?:1.8.0_381]
[16:06:50 FATAL]: Unhandled exception in thread Thread[AWT-EventQueue-0,6,main]
java.lang.NullPointerException: null
	at net.minecraft.launcher.profile.ProfileManager.saveProfiles(ProfileManager.java:66) ~[patched.jar:1.7.2_09]
	at net.minecraft.launcher.SwingUserInterface.showLoginPrompt(SwingUserInterface.java:179) ~[patched.jar:1.7.2_09]
	at net.minecraft.launcher.ui.bottombar.PlayerInfoPanel$1.actionPerformed(PlayerInfoPanel.java:37) ~[patched.jar:1.7.2_09]
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source) ~[?:1.8.0_381]
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source) ~[?:1.8.0_381]
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source) ~[?:1.8.0_381]
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source) ~[?:1.8.0_381]
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source) ~[?:1.8.0_381]
	at java.awt.Component.processMouseEvent(Unknown Source) ~[?:1.8.0_381]
	at javax.swing.JComponent.processMouseEvent(Unknown Source) ~[?:1.8.0_381]
	at java.awt.Component.processEvent(Unknown Source) ~[?:1.8.0_381]
	at java.awt.Container.processEvent(Unknown Source) ~[?:1.8.0_381]
	at java.awt.Component.dispatchEventImpl(Unknown Source) ~[?:1.8.0_381]
	at java.awt.Container.dispatchEventImpl(Unknown Source) ~[?:1.8.0_381]
	at java.awt.Component.dispatchEvent(Unknown Source) ~[?:1.8.0_381]
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source) ~[?:1.8.0_381]
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source) ~[?:1.8.0_381]
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source) ~[?:1.8.0_381]
	at java.awt.Container.dispatchEventImpl(Unknown Source) ~[?:1.8.0_381]
	at java.awt.Window.dispatchEventImpl(Unknown Source) ~[?:1.8.0_381]
	at java.awt.Component.dispatchEvent(Unknown Source) ~[?:1.8.0_381]
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source) ~[?:1.8.0_381]
	at java.awt.EventQueue.access$500(Unknown Source) ~[?:1.8.0_381]
	at java.awt.EventQueue$3.run(Unknown Source) ~[?:1.8.0_381]
	at java.awt.EventQueue$3.run(Unknown Source) ~[?:1.8.0_381]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_381]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source) ~[?:1.8.0_381]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source) ~[?:1.8.0_381]
	at java.awt.EventQueue$4.run(Unknown Source) ~[?:1.8.0_381]
	at java.awt.EventQueue$4.run(Unknown Source) ~[?:1.8.0_381]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_381]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source) ~[?:1.8.0_381]
	at java.awt.EventQueue.dispatchEvent(Unknown Source) ~[?:1.8.0_381]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source) ~[?:1.8.0_381]
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source) ~[?:1.8.0_381]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source) ~[?:1.8.0_381]
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source) ~[?:1.8.0_381]
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source) ~[?:1.8.0_381]
	at java.awt.EventDispatchThread.run(Unknown Source) ~[?:1.8.0_381]
[16:08:10 ERROR]: Failed to open link /2019/04/22/village-and-pillage.html
java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_381]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_381]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_381]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_381]
	at com.mojang.launcher.OperatingSystem.openLink(OperatingSystem.java:67) ~[patched.jar:1.7.2_09]
	at net.minecraft.launcher.ui.tabs.website.JFXBrowser$1$1$1.handleEvent(JFXBrowser.java:66) ~[patched.jar:1.7.2_09]
	at com.sun.webkit.dom.EventListenerImpl.fwkHandleEvent(EventListenerImpl.java:129) ~[jfxrt.jar:?]
	at com.sun.webkit.WebPage.twkProcessMouseEvent(Native Method) ~[jfxrt.jar:?]
	at com.sun.webkit.WebPage.dispatchMouseEvent(WebPage.java:832) ~[jfxrt.jar:?]
	at javafx.scene.web.WebView.processMouseEvent(WebView.java:1048) ~[jfxrt.jar:?]
	at javafx.scene.web.WebView.lambda$registerEventHandlers$3(WebView.java:1171) ~[jfxrt.jar:?]
	at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218) ~[jfxrt.jar:?]
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80) ~[jfxrt.jar:?]
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238) ~[jfxrt.jar:?]
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191) ~[jfxrt.jar:?]
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59) ~[jfxrt.jar:?]
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58) ~[jfxrt.jar:?]
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) ~[jfxrt.jar:?]
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56) ~[jfxrt.jar:?]
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) ~[jfxrt.jar:?]
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56) ~[jfxrt.jar:?]
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) ~[jfxrt.jar:?]
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74) ~[jfxrt.jar:?]
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54) ~[jfxrt.jar:?]
	at javafx.event.Event.fireEvent(Event.java:198) ~[jfxrt.jar:?]
	at javafx.scene.Scene$MouseHandler.process(Scene.java:3760) ~[jfxrt.jar:?]
	at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3488) ~[jfxrt.jar:?]
	at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1765) ~[jfxrt.jar:?]
	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2497) ~[jfxrt.jar:?]
	at com.sun.javafx.tk.quantum.EmbeddedScene.lambda$null$4(EmbeddedScene.java:267) ~[jfxrt.jar:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_381]
	at com.sun.javafx.tk.quantum.EmbeddedScene.lambda$mouseEvent$5(EmbeddedScene.java:255) ~[jfxrt.jar:?]
	at com.sun.javafx.application.PlatformImpl.lambda$null$5(PlatformImpl.java:295) ~[jfxrt.jar:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_381]
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$6(PlatformImpl.java:294) ~[jfxrt.jar:?]
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95) ~[jfxrt.jar:?]
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method) ~[jfxrt.jar:?]
	at com.sun.glass.ui.win.WinApplication.lambda$null$4(WinApplication.java:185) ~[jfxrt.jar:?]
	at java.lang.Thread.run(Unknown Source) ~[?:1.8.0_381]
Caused by: java.io.IOException: Failed to open /2019/04/22/village-and-pillage.html. Error message: The system cannot find the file specified.

	at sun.awt.windows.WDesktopPeer.ShellExecute(Unknown Source) ~[?:1.8.0_381]
	at sun.awt.windows.WDesktopPeer.browse(Unknown Source) ~[?:1.8.0_381]
	at java.awt.Desktop.browse(Unknown Source) ~[?:1.8.0_381]
	... 39 more`
Devs please fix.

**Comment by manOnWebs** [comment]
Nevermind i should delete launcher-profiles.json
