### ISSUE TITLE
Minecraft version 1.8.9 fails to launch. Other versions work fine

### ISSUE THREAD

**Issue by ZyrinDoc** [olauncher/olauncher#5]
I've been having this issue whilst trying to launch Minecraft 1.8.9 from OLauncher. I've tried version 1.12 on OLauncher for it to launch successfully yet I cannot get 1.8.9 to launch.

The game will launch for a split second then will crash showing the following error in the log file:
`Exception in thread "main" com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated array at line 1 column 575
	at com.google.gson.internal.Streams.parse(Streams.java:56)
	at com.google.gson.TreeTypeAdapter.read(TreeTypeAdapter.java:54)
	at com.google.gson.Gson.fromJson(Gson.java:803)
	at com.google.gson.Gson.fromJson(Gson.java:768)
	at com.google.gson.Gson.fromJson(Gson.java:717)
	at com.google.gson.Gson.fromJson(Gson.java:689)
	at net.minecraft.client.main.Main.main(SourceFile:90)
Caused by: com.google.gson.stream.MalformedJsonException: Unterminated array at line 1 column 575
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1505)
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:465)
	at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:403)
	at com.google.gson.internal.bind.TypeAdapters$25.read(TypeAdapters.java:658)
	at com.google.gson.internal.bind.TypeAdapters$25.read(TypeAdapters.java:667)
	at com.google.gson.internal.bind.TypeAdapters$25.read(TypeAdapters.java:642)
	at com.google.gson.internal.Streams.parse(Streams.java:44)
	... 6 more
`

I've tried launching 1.8.9 on several different computers all with different Java versions all to come to the same conclusion.

Looking at the error log it seems that it is trying to contact a server at Google to get a JSON file and it is coming back corrupted or the server doesn't exist anymore. 

Here is a video of what happens:

[Video](https://www.youtube.com/watch?v=AZu611ARgH8)

**Comment by bigfoot547** [comment]
Sorry for getting back to you so late. I believe I have seen this error before, and it relates to either Java or Windows truncating the command line for Minecraft (which is very long). It only happens on Windows from what I can tell.

I will be out of the house for today, but tonight I will try and investigate a solution.

**Comment by bigfoot547** [comment]
(probably) fixed in 0965d8e6e3c03f4e1eb65adfd95df9ff4b4abcd0
