### ISSUE TITLE
java.io.FileNotFoundException: F:\Minecraft\.minecraft\assets\indexes\12.json (The system cannot find the specified file)

### ISSUE THREAD

**Issue by Barni25** [olauncher/olauncher#51]
I am trying to make minecraft playable from an usb stick but i get the following error:

Fatal error launching game. Report this to https://github.com/olauncher/olauncher/issues/new please!
java.io.FileNotFoundException: F:\Minecraft\.minecraft\assets\indexes\12.json (The system cannot find the specified file)
	at java.io.FileInputStream.open0(Native Method) ~[?:?]
	at java.io.FileInputStream.open(FileInputStream.java:216) ~[?:?]
	at java.io.FileInputStream.<init>(FileInputStream.java:157) ~[?:?]
	at org.apache.commons.io.FileUtils.openInputStream(FileUtils.java:2388) ~[patched.jar:1.7.2_10]
	at org.apache.commons.io.FileUtils.readFileToString(FileUtils.java:2506) ~[patched.jar:1.7.2_10]
	at net.minecraft.launcher.Launcher.cleanupOrphanedAssets(Launcher.java:362) ~[patched.jar:1.7.2_10]
	at net.minecraft.launcher.Launcher.performCleanups(Launcher.java:615) ~[patched.jar:1.7.2_10]
	at net.minecraft.launcher.game.MinecraftGameRunner.launchGame(MinecraftGameRunner.java:219) ~[patched.jar:1.7.2_10]
	at com.mojang.launcher.game.runner.AbstractGameRunner.onDownloadJobFinished(AbstractGameRunner.java:292) ~[patched.jar:1.7.2_10]
	at com.mojang.launcher.updater.download.DownloadJob.popAndDownload(DownloadJob.java:150) ~[patched.jar:1.7.2_10]
	at com.mojang.launcher.updater.download.DownloadJob.access$000(DownloadJob.java:16) ~[patched.jar:1.7.2_10]
	at com.mojang.launcher.updater.download.DownloadJob$1.run(DownloadJob.java:111) ~[patched.jar:1.7.2_10]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

I use the followings:
fabric-loader-0.15.3-1.20.2
fabric-api-0.91.3+1.20.2
sodium-fabric-mc1.20.2-0.5.5

Here is my log file from logs folder:
[latest.log](https://github.com/olauncher/olauncher/files/13866624/latest.log)

And my crash file from crash-reports:
[crash-2024-01-08_23.05.46-client.txt](https://github.com/olauncher/olauncher/files/13866668/crash-2024-01-08_23.05.46-client.txt)

**Comment by JanGamesHD** [comment]
Are you using the workDir argument?

**Comment by Barni25** [comment]
Yes, here is my launch bat file:

@echo off
"%CD%\.minecraft\olauncher-1.7.2_10-redist.jar" --workDir "%CD%\.minecraft"
pause

**Comment by Barni25** [comment]
I forgot that Sodium doesn't like Riva Tuner...
I closed Riva Tuner and minecraft is launched, but i still getting warnings.

**Comment by bigfoot547** [comment]
Please make a new issue if you have any more issues. Thanks.
