### ISSUE TITLE
Microsoft login issue

### ISSUE THREAD

**Issue by cloudwithax** [olauncher/olauncher#57]
I'm unable to login via Microsoft with the launcher

output of `java --version`:

```
openjdk 17.0.10 2024-01-16
OpenJDK Runtime Environment Temurin-17.0.10+7 (build 17.0.10+7)
OpenJDK 64-Bit Server VM Temurin-17.0.10+7 (build 17.0.10+7, mixed mode, sharing)
```

Error:
```
java.lang.IllegalArgumentException: Name and ID cannot both be blank
        at com.mojang.authlib.GameProfile.<init>(GameProfile.java:16) ~[patched.jar:1.7.2_10]
        at dev.figboot.olauncher.auth.MicrosoftUserAuthentication.profileLogIn(MicrosoftUserAuthentication.java:215) ~[patched.jar:1.7.2_10]
        at dev.figboot.olauncher.auth.MicrosoftUserAuthentication.logIn(MicrosoftUserAuthentication.java:133) ~[patched.jar:1.7.2_10]
        at net.minecraft.launcher.ui.popups.login.LogInForm$4.run(LogInForm.java:168) ~[patched.jar:1.7.2_10]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
        at java.lang.Thread.run(Unknown Source) ~[?:?]
```

**Comment by JanGamesHD** [comment]
I´ve posted a fix here: 
https://github.com/olauncher/olauncher/issues/52

**Comment by SpareEnderboy** [comment]
nobody:
java 8:
`[18:06:19 ERROR]: Unable to start login server
java.net.BindException: Address already in use: JVM_Bind
        at java.net.DualStackPlainSocketImpl.bind0(Native Method)
        at java.net.DualStackPlainSocketImpl.socketBind(Unknown Source)
        at java.net.AbstractPlainSocketImpl.bind(Unknown Source)
        at java.net.PlainSocketImpl.bind(Unknown Source)
        at java.net.ServerSocket.bind(Unknown Source)
        at java.net.ServerSocket.<init>(Unknown Source)
        at dev.figboot.olauncher.auth.MSLoginServer.<init>(MSLoginServer.java:64)
        at dev.figboot.olauncher.auth.ui.MSLoginDialog.<init>(MSLoginDialog.java:80)
        at net.minecraft.launcher.ui.popups.login.LogInForm.lambda$openMSLogin$0(LogInForm.java:222)
        at java.awt.event.InvocationEvent.dispatch(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)`

**Comment by bigfoot547** [comment]
@SpareEnderboy yeah this is a known unfixable issue. We're going to change how auth works in the next update to sidestep this problem and hopefully some other jank.

**Comment by exrodev** [comment]
I have now provided a work around in the case that any user has this issue again.

**Comment by SpareEnderboy** [comment]
why is this marked off topic its literaly the error message i got in the terminal
> nobody:
java 8: `[18:06:19 ERROR]: Unable to start login server java.net.BindException: Address already in use: JVM_Bind at java.net.DualStackPlainSocketImpl.bind0(Native Method)`

**Comment by JanGamesHD** [comment]
That usually means that the port for receiving the code is already in use. Maybe some other application installed on your PC is using it?
