### ISSUE TITLE
Stuck on loading when launching OLauncher

### ISSUE THREAD

**Issue by thehydrogen** [olauncher/olauncher#6]
Launcher error log

```
[14:32:39 ERROR]: Unexpected exception refreshing profile list
java.lang.NullPointerException: null
	at net.minecraft.launcher.Launcher$2.run(Launcher.java:213) ~[patched.jar:1.7.2_04]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_322]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_322]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_322]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_322]
	at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_322]
[14:32:39 ERROR]: Unhandled exception in executor com.mojang.launcher.updater.ExceptionalThreadPoolExecutor$ExceptionalFutureTask@60f67cea
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_322]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_322]
	at com.mojang.launcher.updater.ExceptionalThreadPoolExecutor$ExceptionalFutureTask.done(ExceptionalThreadPoolExecutor.java:60) ~[patched.jar:1.7.2_04]
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:384) ~[?:1.8.0_322]
	at java.util.concurrent.FutureTask.setException(FutureTask.java:251) ~[?:1.8.0_322]
	at java.util.concurrent.FutureTask.run(FutureTask.java:271) ~[?:1.8.0_322]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_322]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_322]
	at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_322]
Caused by: java.lang.NullPointerException
	at net.minecraft.launcher.profile.ProfileManager.saveProfiles(ProfileManager.java:66) ~[patched.jar:1.7.2_04]
	at net.minecraft.launcher.SwingUserInterface.showLoginPrompt(SwingUserInterface.java:177) ~[patched.jar:1.7.2_04]
	at net.minecraft.launcher.Launcher.ensureLoggedIn(Launcher.java:266) ~[patched.jar:1.7.2_04]
	at net.minecraft.launcher.Launcher$2.run(Launcher.java:242) ~[patched.jar:1.7.2_04]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_322]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_322]
	... 3 more
[14:32:39 FATAL]: Unhandled exception in thread Thread[AWT-EventQueue-0,6,main]
java.lang.NullPointerException: null
	at net.minecraft.launcher.ui.bottombar.ProfileSelectionPanel.populateProfiles(ProfileSelectionPanel.java:81) ~[patched.jar:1.7.2_04]
	at net.minecraft.launcher.ui.bottombar.ProfileSelectionPanel$1.run(ProfileSelectionPanel.java:75) ~[patched.jar:1.7.2_04]
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311) ~[?:1.8.0_322]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758) ~[?:1.8.0_322]
	at java.awt.EventQueue.access$500(EventQueue.java:97) ~[?:1.8.0_322]
	at java.awt.EventQueue$3.run(EventQueue.java:709) ~[?:1.8.0_322]
	at java.awt.EventQueue$3.run(EventQueue.java:703) ~[?:1.8.0_322]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_322]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74) ~[?:1.8.0_322]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728) ~[?:1.8.0_322]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205) ~[?:1.8.0_322]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) ~[?:1.8.0_322]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) ~[?:1.8.0_322]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) ~[?:1.8.0_322]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) ~[?:1.8.0_322]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) ~[?:1.8.0_322]
```

Running Ubuntu 21.10

**Comment by bigfoot547** [comment]
You have a profile from the new launcher in your launcher_profiles.json. Maybe I should make it so that new profiles are silently ignored.
