### ISSUE TITLE
Invalid max heap size

### ISSUE THREAD

**Issue by Alex-x90** [olauncher/olauncher#75]
When I try to launch it fails to create the virtual machine and checking the logs shows this:
```
Invalid maximum heap size: -Xmx4G
The specified size exceeds the maximum representable size.
```

JVM args being used for this profile: `-Xmx4G -Xms4G -Xmn128M -Xincgc -XX:+UseConcMarkSweepGC -XX:ConcGCThreads=4 -XX:PermSize=64m -XX:MaxPermSize=256m`

However the exact same profile is able to be launched properly from the standard launcher

**Comment by JanGamesHD** [comment]
You most likely have a 32 Bit Version of Java installed. Can you send the launcher log?

**Comment by Alex-x90** [comment]
```
[10:11:20 INFO]: Launching game
[10:11:20 INFO]: Unpacking natives to C:\Users\sasha\AppData\Roaming\.minecraft\versions\1.8.9-forge1.8.9-11.15.1.2318-1.8.9\1.8.9-forge1.8.9-11.15.1.2318-1.8.9-natives-1669659285886400
[10:11:20 INFO]: Launching in C:\Users\sasha\AppData\Roaming\.minecraft
[10:11:20 INFO]: Half command: C:\Users\sasha\AppData\Roaming\.minecraft\olruntime\windows-x86\jre-legacy\runtime\bin\javaw.exe -Xmx4G -Xms4G -Xmn128M -Xincgc -XX:+UseConcMarkSweepGC -XX:ConcGCThreads=4 -XX:PermSize=64m -XX:MaxPermSize=256m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Djava.library.path=C:\Users\sasha\AppData\Roaming\.minecraft\versions\1.8.9-forge1.8.9-11.15.1.2318-1.8.9\1.8.9-forge1.8.9-11.15.1.2318-1.8.9-natives-1669659285886400 -Dminecraft.launcher.brand=java-minecraft-launcher -Dminecraft.launcher.version=1.7.3 -Dminecraft.client.jar=C:\Users\sasha\AppData\Roaming\.minecraft\versions\1.8.9\1.8.9.jar -cp C:\Users\sasha\AppData\Roaming\.minecraft\libraries\net\minecraftforge\forge\1.8.9-11.15.1.2318-1.8.9\forge-1.8.9-11.15.1.2318-1.8.9.jar;C:\Users\sasha\AppData\Roaming\.minecraft\libraries\net\minecraft\launchwrapper\1.12\launchwrapper-1.12.jar;C:\Users\sasha\AppData\Roaming\.minecraft\libraries\org\ow2\asm\asm-all\5.0.3\asm-all-5.0.3.jar;C:\Users\sasha\AppData\Roaming\.minecraft\libraries\jline\jline\2.13\jline-2.13.jar;C:\Users\sasha\AppData\Roaming\.minecraft\libraries\com\typesafe\akka\akka-actor_2.11\2.3.3\akka-actor_2.11-2.3.3.jar;C:\Users\sasha\AppData\Roaming\.minecraft\libraries\com\typesafe\config\1.2.1\config-1.2.1.jar;C:\Users\sasha\AppData\Roaming\.minecraft\libraries\org\scala-lang\scala-actors-migration_2.11\1.1.0\scala-actors-migration_2.11-1.1.0.jar;C:\Users\sasha\AppData\Roaming\.minecraft\libraries\org\scala-lang\scala-compiler\2.11.1\scala-compiler-2.11.1.jar;C:\Users\sasha\AppData\Roaming\.minecraft\libraries\org\scala-lang\plugins\scala-continuations-library_2.11\1.0.2\scala-continuations-library_2.11-1.0.2.jar;C:\Users\sasha\AppData\Roaming\.minecraft\libraries\org\scala-lang\plugins\scala-continuations-plugin_2.11.1\1.0.2\scala-continuations-plugin_2.11.1-1.0.2.jar;C:\Users\sasha\AppData\Roaming\.minecraft\libraries\org\scala-lang\scala-library\2.11.1\scala-library-2.11.1.jar;C:\Users\sasha\AppData\Roaming\.minecraft\libraries\org\scala-lang\scala-parser-combinators_2.11\1.0.1\scala-parser-combinators_2.11-1.0.1.jar;C:\Users\sasha\AppData\Roaming\.minecraft\libraries\org\scala-lang\scala-reflect\2.11.1\scala-reflect-2.11.1.jar;C:\Users\sasha\AppData\Roaming\.minecraft\libraries\org\scala-lang\scala-swing_2.11\1.0.1\scala-swing_2.11-1.0.1.jar;C:\Users\sasha\AppData\Roaming\.minecraft\libraries\org\scala-lang\scala-xml_2.11\1.0.2\scala-xml_2.11-1.0.2.jar;C:\Users\sasha\AppData\Roaming\.minecraft\libraries\lzma\lzma\0.0.1\lzma-0.0.1.jar;C:\Users\sasha\AppData\Roaming\.minecraft\libraries\net\sf\jopt-simple\jopt-simple\4.6\jopt-simple-4.6.jar;C:\Users\sasha\AppData\Roaming\.minecraft\libraries\java3d\vecmath\1.5.2\vecmath-1.5.2.jar;C:\Users\sasha\AppData\Roaming\.minecraft\libraries\net\sf\trove4j\trove4j\3.0.3\trove4j-3.0.3.jar;C:\Users\sasha\AppData\Roaming\.minecraft\libraries\com\mojang\netty\1.8.8\netty-1.8.8.jar;C:\Users\sasha\AppData\Roaming\.minecraft\libraries\oshi-project\oshi-core\1.1\oshi-core-1.1.jar;C:\Users\sasha\AppData\Roaming\.minecraft\libraries\net\java\dev\jna\jna\3.4.0\jna-3.4.0.jar;C:\Users\sasha\AppData\Roaming\.minecraft\libraries\net\java\dev\jna\platform\3.4.0\platform-3.4.0.jar;C:\Users\sasha\AppData\Roaming\.minecraft\libraries\com\ibm\icu\icu4j-core-mojang\51.2\icu4j-core-mojang-51.2.jar;C:\Users\sasha\AppData\Roaming\.minecraft\libraries\net\sf\jopt-simple\jopt-simple\4.6\jopt-simple-4.6.jar;C:\Users\sasha\AppData\Roaming\.minecraft\libraries\com\paulscode\codecjorbis\20101023\codecjorbis-20101023.jar;C:\Users\sasha\AppData\Roaming\.minecraft\libraries\com\paulscode\codecwav\20101023\codecwav-20101023.jar;C:\Users\sasha\AppData\Roaming\.minecraft\libraries\com\paulscode\libraryjavasound\20101123\libraryjavasound-20101123.jar;C:\Users\sasha\AppData\Roaming\.minecraft\libraries\com\paulscode\librarylwjglopenal\20100824\librarylwjglopenal-20100824.jar;C:\Users\sasha\AppData\Roaming\.minecraft\libraries\com\paulscode\soundsystem\20120107\soundsystem-20120107.jar;C:\Users\sasha\AppData\Roaming\.minecraft\libraries\io\netty\netty-all\4.0.23.Final\netty-all-4.0.23.Final.jar;C:\Users\sasha\AppData\Roaming\.minecraft\libraries\com\google\guava\guava\17.0\guava-17.0.jar;C:\Users\sasha\AppData\Roaming\.minecraft\libraries\org\apache\commons\commons-lang3\3.3.2\commons-lang3-3.3.2.jar;C:\Users\sasha\AppData\Roaming\.minecraft\libraries\commons-io\commons-io\2.4\commons-io-2.4.jar;C:\Users\sasha\AppData\Roaming\.minecraft\libraries\commons-codec\commons-codec\1.9\commons-codec-1.9.jar;C:\Users\sasha\AppData\Roaming\.minecraft\libraries\net\java\jinput\jinput\2.0.5\jinput-2.0.5.jar;C:\Users\sasha\AppData\Roaming\.minecraft\libraries\net\java\jutils\jutils\1.0.0\jutils-1.0.0.jar;C:\Users\sasha\AppData\Roaming\.minecraft\libraries\com\google\code\gson\gson\2.2.4\gson-2.2.4.jar;C:\Users\sasha\AppData\Roaming\.minecraft\libraries\com\mojang\authlib\1.5.21\authlib-1.5.21.jar;C:\Users\sasha\AppData\Roaming\.minecraft\libraries\com\mojang\realms\1.7.59\realms-1.7.59.jar;C:\Users\sasha\AppData\Roaming\.minecraft\libraries\org\apache\commons\commons-compress\1.8.1\commons-compress-1.8.1.jar;C:\Users\sasha\AppData\Roaming\.minecraft\libraries\org\apache\httpcomponents\httpclient\4.3.3\httpclient-4.3.3.jar;C:\Users\sasha\AppData\Roaming\.minecraft\libraries\commons-logging\commons-logging\1.1.3\commons-logging-1.1.3.jar;C:\Users\sasha\AppData\Roaming\.minecraft\libraries\org\apache\httpcomponents\httpcore\4.3.2\httpcore-4.3.2.jar;C:\Users\sasha\AppData\Roaming\.minecraft\libraries\org\apache\logging\log4j\log4j-api\2.0-beta9\log4j-api-2.0-beta9.jar;C:\Users\sasha\AppData\Roaming\.minecraft\libraries\org\apache\logging\log4j\log4j-core\2.0-beta9\log4j-core-2.0-beta9.jar;C:\Users\sasha\AppData\Roaming\.minecraft\libraries\org\lwjgl\lwjgl\lwjgl\2.9.4-nightly-20150209\lwjgl-2.9.4-nightly-20150209.jar;C:\Users\sasha\AppData\Roaming\.minecraft\libraries\org\lwjgl\lwjgl\lwjgl_util\2.9.4-nightly-20150209\lwjgl_util-2.9.4-nightly-20150209.jar;C:\Users\sasha\AppData\Roaming\.minecraft\libraries\tv\twitch\twitch\6.5\twitch-6.5.jar;C:\Users\sasha\AppData\Roaming\.minecraft\versions\1.8.9\1.8.9.jar net.minecraft.launchwrapper.Launch
[10:11:20 INFO]: Looking for orphaned versions to clean up...
[10:11:20 FATAL]: Fatal error launching game. Report this to https://github.com/olauncher/olauncher/issues/new please!
java.io.FileNotFoundException: C:\Users\sasha\AppData\Roaming\.minecraft\assets\indexes\1.15.json (The system cannot find the file specified)
	at java.io.FileInputStream.open0(Native Method) ~[?:1.8.0_321]
	at java.io.FileInputStream.open(Unknown Source) ~[?:1.8.0_321]
	at java.io.FileInputStream.<init>(Unknown Source) ~[?:1.8.0_321]
	at org.apache.commons.io.FileUtils.openInputStream(FileUtils.java:2388) ~[patched.jar:1.7.3]
	at org.apache.commons.io.FileUtils.readFileToString(FileUtils.java:2506) ~[patched.jar:1.7.3]
	at net.minecraft.launcher.Launcher.cleanupOrphanedAssets(Launcher.java:362) ~[patched.jar:1.7.3]
	at net.minecraft.launcher.Launcher.performCleanups(Launcher.java:615) ~[patched.jar:1.7.3]
	at net.minecraft.launcher.game.MinecraftGameRunner.launchGame(MinecraftGameRunner.java:219) ~[patched.jar:1.7.3]
	at com.mojang.launcher.game.runner.AbstractGameRunner.onDownloadJobFinished(AbstractGameRunner.java:292) ~[patched.jar:1.7.3]
	at com.mojang.launcher.updater.download.DownloadJob.popAndDownload(DownloadJob.java:150) ~[patched.jar:1.7.3]
	at com.mojang.launcher.updater.download.DownloadJob.access$000(DownloadJob.java:16) ~[patched.jar:1.7.3]
	at com.mojang.launcher.updater.download.DownloadJob$1.run(DownloadJob.java:111) ~[patched.jar:1.7.3]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_321]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_321]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:1.8.0_321]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:1.8.0_321]
	at java.lang.Thread.run(Unknown Source) ~[?:1.8.0_321]
[10:11:21 ERROR]: Game ended with bad state (exit code 1)
[10:11:21 INFO]: Ignoring visibility rule and showing launcher due to a game crash
[10:11:21 INFO]: Deleting C:\Users\sasha\AppData\Roaming\.minecraft\versions\1.8.9-forge1.8.9-11.15.1.2318-1.8.9\1.8.9-forge1.8.9-11.15.1.2318-1.8.9-natives-1669659285886400
```

**Comment by bigfoot547** [comment]
scroll up to the top of the launcher log and send us that
it contains system and java runtime information

**Comment by Alex-x90** [comment]
Ah yeah, assuming `sun.arch.data.model` is 32 vs. 64 bit, it's the 32bit version
```
[10:11:16 INFO]: OLauncher 1.7.3 (through bootstrap 100) started on windows...
[10:11:16 INFO]: Current time is Apr 29, 2024 10:11:16 AM
[10:11:16 INFO]: System.getProperty('os.name') == 'Windows 10'
[10:11:16 INFO]: System.getProperty('os.version') == '10.0'
[10:11:16 INFO]: System.getProperty('os.arch') == 'x86'
[10:11:16 INFO]: System.getProperty('java.version') == '1.8.0_321'
[10:11:16 INFO]: System.getProperty('java.vendor') == 'Oracle Corporation'
[10:11:16 INFO]: System.getProperty('sun.arch.data.model') == '32'
```

**Comment by bigfoot547** [comment]
right. when you use the 32 bit version of the launcher, it will attempt to use a 32 bit version of java to run the game, which is insufficient in your case. Try downloading 64 bit java (from java.com perhaps?) and running the launcher using that

**Comment by Alex-x90** [comment]
It worked but java seems to have messed up the .jar file association/launching via double click. I can manually launch with `java -jar olauncher-1.7.3-redist.jar` though, and I usually start the launcher with a macro anyways so this is probably acceptable. (anyways this is a java problem not a problem with the launcher, so issue fixed)
