### ISSUE TITLE
Error with Microsoft authentication

### ISSUE THREAD

**Issue by vico93** [olauncher/olauncher#83]
I had logged with my MS Account a week ago approx, and the last couple of days when opening the launcher when trying to authenticate it spilled the following lines:

```log
[18:10:46 INFO]: Mojang token valid, fetching profile...
[18:10:47 ERROR]: Unhandled exception in executor com.mojang.launcher.updater.ExceptionalThreadPoolExecutor$ExceptionalFutureTask@2ae2293a[Completed exceptionally: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $]
java.util.concurrent.ExecutionException: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:?]
	at java.util.concurrent.FutureTask.get(FutureTask.java:191) ~[?:?]
	at com.mojang.launcher.updater.ExceptionalThreadPoolExecutor$ExceptionalFutureTask.done(ExceptionalThreadPoolExecutor.java:60) ~[patched.jar:1.7.3_01]
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:434) ~[?:?]
	at java.util.concurrent.FutureTask.setException(FutureTask.java:303) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:322) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:225) ~[patched.jar:1.7.3_01]
	at com.google.gson.Gson.fromJson(Gson.java:991) ~[patched.jar:1.7.3_01]
	at com.google.gson.Gson.fromJson(Gson.java:956) ~[patched.jar:1.7.3_01]
	at com.google.gson.Gson.fromJson(Gson.java:905) ~[patched.jar:1.7.3_01]
	at com.google.gson.Gson.fromJson(Gson.java:876) ~[patched.jar:1.7.3_01]
	at dev.figboot.olauncher.auth.MicrosoftAuthenticationService.lambda$getAuthenticated$3(MicrosoftAuthenticationService.java:167) ~[patched.jar:1.7.3_01]
	at dev.figboot.olauncher.auth.MicrosoftAuthenticationService.readResponse(MicrosoftAuthenticationService.java:109) ~[patched.jar:1.7.3_01]
	at dev.figboot.olauncher.auth.MicrosoftAuthenticationService.makeRequest(MicrosoftAuthenticationService.java:144) ~[patched.jar:1.7.3_01]
	at dev.figboot.olauncher.auth.MicrosoftAuthenticationService.getAuthenticated(MicrosoftAuthenticationService.java:167) ~[patched.jar:1.7.3_01]
	at dev.figboot.olauncher.auth.MicrosoftUserAuthentication.ownsGame(MicrosoftUserAuthentication.java:148) ~[patched.jar:1.7.3_01]
	at dev.figboot.olauncher.auth.MicrosoftUserAuthentication.profileLogIn(MicrosoftUserAuthentication.java:270) ~[patched.jar:1.7.3_01]
	at dev.figboot.olauncher.auth.MicrosoftUserAuthentication.logIn(MicrosoftUserAuthentication.java:127) ~[patched.jar:1.7.3_01]
	at net.minecraft.launcher.Launcher.ensureLoggedIn(Launcher.java:294) ~[patched.jar:1.7.3_01]
	at net.minecraft.launcher.Launcher$2.run(Launcher.java:247) ~[patched.jar:1.7.3_01]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
	... 3 more
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:385) ~[patched.jar:1.7.3_01]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:214) ~[patched.jar:1.7.3_01]
	at com.google.gson.Gson.fromJson(Gson.java:991) ~[patched.jar:1.7.3_01]
	at com.google.gson.Gson.fromJson(Gson.java:956) ~[patched.jar:1.7.3_01]
	at com.google.gson.Gson.fromJson(Gson.java:905) ~[patched.jar:1.7.3_01]
	at com.google.gson.Gson.fromJson(Gson.java:876) ~[patched.jar:1.7.3_01]
	at dev.figboot.olauncher.auth.MicrosoftAuthenticationService.lambda$getAuthenticated$3(MicrosoftAuthenticationService.java:167) ~[patched.jar:1.7.3_01]
	at dev.figboot.olauncher.auth.MicrosoftAuthenticationService.readResponse(MicrosoftAuthenticationService.java:109) ~[patched.jar:1.7.3_01]
	at dev.figboot.olauncher.auth.MicrosoftAuthenticationService.makeRequest(MicrosoftAuthenticationService.java:144) ~[patched.jar:1.7.3_01]
	at dev.figboot.olauncher.auth.MicrosoftAuthenticationService.getAuthenticated(MicrosoftAuthenticationService.java:167) ~[patched.jar:1.7.3_01]
	at dev.figboot.olauncher.auth.MicrosoftUserAuthentication.ownsGame(MicrosoftUserAuthentication.java:148) ~[patched.jar:1.7.3_01]
	at dev.figboot.olauncher.auth.MicrosoftUserAuthentication.profileLogIn(MicrosoftUserAuthentication.java:270) ~[patched.jar:1.7.3_01]
	at dev.figboot.olauncher.auth.MicrosoftUserAuthentication.logIn(MicrosoftUserAuthentication.java:127) ~[patched.jar:1.7.3_01]
	at net.minecraft.launcher.Launcher.ensureLoggedIn(Launcher.java:294) ~[patched.jar:1.7.3_01]
	at net.minecraft.launcher.Launcher$2.run(Launcher.java:247) ~[patched.jar:1.7.3_01]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
	... 3 more
```
With the original launcher (that i ran with a different folder with `--workDir`) it works fine.

**Comment by bigfoot547** [comment]
hmm this is strange and new. Does this happen when you run OLauncher in a clean directory with `--workDir`? I don't understand the last sentence of your post.

**Comment by sunnydayoutside** [comment]
I'm having this same issue. I thought it was an issue with my firewall but logs show the same thing.
![image](https://github.com/olauncher/olauncher/assets/59892936/98f2b6ee-e181-483f-9e6d-b928d7267aa5)

**Comment by bigfoot547** [comment]
that's odd, I can't reproduce that

**Comment by vico93** [comment]
Strangely after a couple of tries the launcher seems to get auth'd correctly. Dont know what caused that (right after the error happened i've opened the original launcher and it ran correctly, so not much chance to be a Microsoft/Mojang issue)

**Comment by vico93** [comment]
More information about this: after trying until exhaustion to open-close-open olauncher until the error stops working and not being successful, i tried "Switch User", and when clicking in "Microsoft Login" it simply freezes in place in eternal loading. Opening the launcher again seems to have me disconnected, so i tried "Microsoft Login" again, since i was already logged in my MSA on my browser and did consent to olauncher, it just tell me to close the tab and go back to the launcher, but on there the same never-ending loading happens.


For information, my MSA have two-step authentication via Microsoft Authenticator. Could it be a factor?

**Comment by vico93** [comment]
Running olauncher with `java` on Windows Terminal reveals the error after i go back from the browser:

```
[20:32:03 FATAL]: Unhandled exception in thread Thread[#53,pool-2-thread-2,5,main]
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:225) ~[patched.jar:1.7.3_01]
        at com.google.gson.Gson.fromJson(Gson.java:991) ~[patched.jar:1.7.3_01]
        at com.google.gson.Gson.fromJson(Gson.java:956) ~[patched.jar:1.7.3_01]
        at com.google.gson.Gson.fromJson(Gson.java:905) ~[patched.jar:1.7.3_01]
        at com.google.gson.Gson.fromJson(Gson.java:876) ~[patched.jar:1.7.3_01]
        at dev.figboot.olauncher.auth.MicrosoftAuthenticationService.lambda$getAuthenticated$3(MicrosoftAuthenticationService.java:167) ~[patched.jar:1.7.3_01]
        at dev.figboot.olauncher.auth.MicrosoftAuthenticationService.readResponse(MicrosoftAuthenticationService.java:109) ~[patched.jar:1.7.3_01]
        at dev.figboot.olauncher.auth.MicrosoftAuthenticationService.makeRequest(MicrosoftAuthenticationService.java:144) ~[patched.jar:1.7.3_01]
        at dev.figboot.olauncher.auth.MicrosoftAuthenticationService.getAuthenticated(MicrosoftAuthenticationService.java:167) ~[patched.jar:1.7.3_01]
        at dev.figboot.olauncher.auth.MicrosoftUserAuthentication.profileLogIn(MicrosoftUserAuthentication.java:275) ~[patched.jar:1.7.3_01]
        at dev.figboot.olauncher.auth.MicrosoftUserAuthentication.logIn(MicrosoftUserAuthentication.java:140) ~[patched.jar:1.7.3_01]
        at net.minecraft.launcher.ui.popups.login.LogInForm$2.run(LogInForm.java:165) ~[patched.jar:1.7.3_01]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
        at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:385) ~[patched.jar:1.7.3_01]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:214) ~[patched.jar:1.7.3_01]
        ... 14 more
```

Same thing than before, i think

**Comment by vico93** [comment]
> hmm this is strange and new. Does this happen when you run OLauncher in a clean directory with `--workDir`? I don't understand the last sentence of your post.

Sorry, didnt see this part of your first comment.

I will try to see if running olauncher in another work directory would change things.

About the last sentence, sorry my bad english. What i was trying to say is that i don't get any authenticator issue in the Mojang launcher, i run both side by side but each have its own directory (both with `--workDir` parameters specified).

**Comment by bigfoot547** [comment]
this seems to have been an intermittent Microsoft issue
