### ISSUE TITLE
failure to log in with my microsoft account

### ISSUE THREAD

**Issue by alexisal1984** [olauncher/olauncher#85]
im having a problem logging into my microsoft account
i just recently bought the game and decided to try to install it through this one but i kept getting a 401 error while attempting to log in to my microsoft account

in addition, here is what it spewed out when i ran it through the command prompt:

[01:26:00 INFO]: OLauncher 1.7.3_01 (through bootstrap 100) started on windows...
[01:26:00 INFO]: Current time is Jun 11, 2024 1:26:00 AM
[01:26:00 INFO]: System.getProperty('os.name') == 'Windows 10'
[01:26:00 INFO]: System.getProperty('os.version') == '10.0'
[01:26:00 INFO]: System.getProperty('os.arch') == 'x86'
[01:26:00 INFO]: System.getProperty('java.version') == '1.8.0_411'
[01:26:00 INFO]: System.getProperty('java.vendor') == 'Oracle Corporation'
[01:26:00 INFO]: System.getProperty('sun.arch.data.model') == '32'
[01:26:00 INFO]: proxy == DIRECT
[01:26:01 INFO]: Refreshing local version list...
[01:26:01 INFO]: Refreshing remote version list...
[01:26:01 INFO]: It is not time to query releases yet. Wait another 139 minutes.
[01:26:01 INFO]: Latest release is v1.7.3_01 (ID 157441086).
[01:26:01 INFO]: Your java runtime platform is 'windows-x86'.
[01:26:01 INFO]: Finished refreshing java runtime list.
[01:26:02 INFO]: Refresh complete.
[01:26:02 INFO]: Loaded profile Default
[01:26:02 INFO]: Loaded 1 profile(s); selected 'Default'
[01:26:07 INFO]: GET request received (/)
[01:26:07 INFO]: GET request received (/authComplete)
[01:26:07 INFO]: Server thread complete
[01:26:12 ERROR]: Couldn't log in
dev.figboot.olauncher.auth.error.ResponseCodeException: java.io.FileNotFoundException: https://api.minecraftservices.com/minecraft/profile
        at dev.figboot.olauncher.auth.MicrosoftAuthenticationService.readResponse(MicrosoftAuthenticationService.java:111) ~[patched.jar:1.7.3_01]
        at dev.figboot.olauncher.auth.MicrosoftAuthenticationService.makeRequest(MicrosoftAuthenticationService.java:144) ~[patched.jar:1.7.3_01]
        at dev.figboot.olauncher.auth.MicrosoftAuthenticationService.getAuthenticated(MicrosoftAuthenticationService.java:167) ~[patched.jar:1.7.3_01]
        at dev.figboot.olauncher.auth.MicrosoftUserAuthentication.profileLogIn(MicrosoftUserAuthentication.java:275) ~[patched.jar:1.7.3_01]
        at dev.figboot.olauncher.auth.MicrosoftUserAuthentication.logIn(MicrosoftUserAuthentication.java:140) ~[patched.jar:1.7.3_01]
        at net.minecraft.launcher.ui.popups.login.LogInForm$2.run(LogInForm.java:165) ~[patched.jar:1.7.3_01]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:1.8.0_411]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:1.8.0_411]
        at java.lang.Thread.run(Unknown Source) ~[?:1.8.0_411]
Caused by: java.io.FileNotFoundException: https://api.minecraftservices.com/minecraft/profile
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_411]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_411]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_411]
        at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_411]
        at sun.net.www.protocol.http.HttpURLConnection$10.run(Unknown Source) ~[?:1.8.0_411]
        at sun.net.www.protocol.http.HttpURLConnection$10.run(Unknown Source) ~[?:1.8.0_411]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_411]
        at sun.net.www.protocol.http.HttpURLConnection.getChainedException(Unknown Source) ~[?:1.8.0_411]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source) ~[?:1.8.0_411]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source) ~[?:1.8.0_411]
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source) ~[?:1.8.0_411]
        at dev.figboot.olauncher.auth.MicrosoftAuthenticationService.readResponse(MicrosoftAuthenticationService.java:95) ~[patched.jar:1.7.3_01]
        ... 8 more
Caused by: java.io.FileNotFoundException: https://api.minecraftservices.com/minecraft/profile
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source) ~[?:1.8.0_411]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source) ~[?:1.8.0_411]
        at java.net.HttpURLConnection.getResponseCode(Unknown Source) ~[?:1.8.0_411]
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(Unknown Source) ~[?:1.8.0_411]
        at dev.figboot.olauncher.auth.MicrosoftAuthenticationService.readResponse(MicrosoftAuthenticationService.java:90) ~[patched.jar:1.7.3_01]
        ... 8 more

**Comment by notbronwyn** [comment]
MS has been having a stroke and all launchers do this
i’ve heard from someone that prism is also having issues

**Comment by alexisal1984** [comment]
> MS has been having a stroke and all launchers do this i’ve heard from someone that prism is also having issues

huh, does this also include the official launcher as well?

**Comment by bigfoot547** [comment]
make sure that you are using 64 bit java if you are on a 64 bit computer

**Comment by bigfoot547** [comment]
it seems like this was an intermittent issue on Microsoft's side, so I will close this issue

**Comment by Filip-Ignaciuk** [comment]
I had the same issue for both Prisim Launcher and OLauncher for a couple of months now, what worked for me was setting the birthday of your microsoft account before the year 2000, not sure why this worked but it did for me.
